name: yamllint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run yamllint
      uses: actionshub/yamllint@main
